### ISSUE TITLE
Update typefaces

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/v4.chriskrycho.com#72]
- [x] Make the _normal_ body typeface `"Cronos Pro"`
- [x] Add the category as a class to all items; then do:
  
  ``` scss
  article {
      // ... all the existing style ...
  
      &.theology {
          p {
              font: {
                  family: $serif;
                  size: 92%;  // this is just what looks right
              }
          }
      }
  }
  ```
  
  Additionally, tweak the `article header h2`: remove the leading and following `—` characters (`"\2014"`), set `padding-top: 0.33rem`, and set `font-style: italic`.
